"""
LoRaWAN Credential Provisioning for Corona SmartFlux.

Generates or assigns DevEUI, JoinEUI, AppKey, NwkKey for each device.
Credentials follow LoRaWAN 1.0.4 / OTAA conventions.
"""

import os
import hashlib
import secrets


# Default JoinEUI shared across all devices in the application
DEFAULT_JOIN_EUI = "24E124C0002A0001"
DEFAULT_DEVEUI_PREFIX = "70B3D57ED8"  # Sense AI / Corona OUI prefix


class LoRaWANProvisioner:
    """Generates and manages LoRaWAN credentials for STM32WLE5 devices."""

    def __init__(self, join_eui=None, deveui_prefix=None):
        self.join_eui = join_eui or DEFAULT_JOIN_EUI
        self.deveui_prefix = deveui_prefix or DEFAULT_DEVEUI_PREFIX

    # ------------------------------------------------------------------
    # DevEUI generation
    # ------------------------------------------------------------------
    def generate_deveui(self, device_uid_hex):
        """Derive a DevEUI from the 96-bit device UID.

        Strategy: SHA-256 hash of UID, take 3 bytes to combine with OUI prefix
        to form the 8-byte (16 hex char) DevEUI.
        """
        uid_bytes = bytes.fromhex(device_uid_hex)
        digest = hashlib.sha256(uid_bytes).digest()
        suffix = digest[:3].hex().upper()
        deveui = (self.deveui_prefix + suffix).upper()
        return deveui[:16]  # Exactly 8 bytes

    # ------------------------------------------------------------------
    # Key generation
    # ------------------------------------------------------------------
    @staticmethod
    def generate_app_key():
        """Generate a random 128-bit AppKey (32 hex chars)."""
        return secrets.token_hex(16).upper()

    @staticmethod
    def generate_nwk_key(app_key=None):
        """Return the NwkKey.
        For LoRaWAN 1.0.x compatibility, NwkKey == AppKey.
        """
        return app_key if app_key else secrets.token_hex(16).upper()

    # ------------------------------------------------------------------
    # Full credential set
    # ------------------------------------------------------------------
    def provision_device(self, device_uid_hex):
        """Generate a complete set of LoRaWAN credentials for a device.

        Returns dict:
            deveui, joineui, appkey, nwkkey, region, class, activation,
            network_server, application_name
        """
        deveui = self.generate_deveui(device_uid_hex)
        appkey = self.generate_app_key()
        nwkkey = self.generate_nwk_key(appkey)

        return {
            "deveui": deveui,
            "joineui": self.join_eui,
            "appkey": appkey,
            "nwkkey": nwkkey,
            "region": "US915",
            "class": "A",
            "activation": "OTAA",
            "network_server": "The Things Network",
            "application_name": "corona-smartflux-prod",
        }

    # ------------------------------------------------------------------
    # se-identity header generation
    # ------------------------------------------------------------------
    @staticmethod
    def generate_se_identity_header(credentials, serial_number):
        """Generate the se-identity_template.h content for a device."""
        def fmt(hex_str):
            return ",".join(
                f"0x{hex_str[i:i+2]}" for i in range(0, len(hex_str), 2)
            )

        lines = [
            f"// Auto-generated by bootloader for device: {serial_number}",
            f"// Generated: {__import__('datetime').datetime.now(__import__('datetime').timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            "",
            f"#define LORAWAN_DEVICE_EUI    {fmt(credentials['deveui'])}",
            f"#define LORAWAN_JOIN_EUI      {fmt(credentials['joineui'])}",
            f"#define LORAWAN_APP_KEY       {fmt(credentials['appkey'])}",
            f"#define LORAWAN_NWK_KEY       {fmt(credentials['nwkkey'])}",
            "",
        ]
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Format helpers
    # ------------------------------------------------------------------
    @staticmethod
    def format_eui(hex_str, separator="-"):
        """Format a hex EUI string with separators: 70-B3-D5-..."""
        return separator.join(
            hex_str[i:i+2] for i in range(0, len(hex_str), 2)
        )

    @staticmethod
    def format_key(hex_str, separator=" "):
        """Format a 128-bit key with separators for display."""
        return separator.join(
            hex_str[i:i+2] for i in range(0, len(hex_str), 2)
        )
